// <copyright file="GlobalSuppressions.cs" company="Agility E Services">
// Copyright (c) Agility E Services. All rights reserved.
// </copyright>
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S125:Remove this commented out code", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S112:'System.Exception' should not be thrown by user code", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S1226:Introduce a new variable instead of reusing the parameter", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S2360:Use the overloading mechanism instead of the optional parameters", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S126:Add the missing 'else' clause", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S1449:Define the locale to be used in this string operation", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S3254:Remove this default value assigned to parameter", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S107:which is greater than the 7 authorized", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S3874:Consider refactoring this method in order to remove the need for this 'ref' modifier", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S3996:Change this property type to 'System.Uri'", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S2228:Remove this logging statement", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S2278:Use the recommended AES (Advanced Encryption Standard) instead", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S2068:Remove hard-coded password(s): 'password'", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S4018:Refactor this method to have parameters matching all the type parameters", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S3995:Change this return type to 'System.Uri'", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S3994:Either change this parameter type to 'System.Uri' or provide an overload which takes a 'System.Uri' parameter", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S2070:Use a stronger hashing/asymmetric algorithm", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S4005:Call the overload that takes a 'System.Uri' as an argument instead", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S100:Rename method 'GetHashHMACSHA256OfString' to match camel case naming rules, consider using 'GetHashHmacsha256OfString'", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S1227:Refactor the code in order to remove this break statement", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S4017:Refactor this method to remove the nested type argument", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S1450:field and declare it as a local variable in the relevant methods", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S2436:Reduce the number of generic parameters in the", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S1541:The Cyclomatic Complexity of this method is", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S2326:is not used in the method", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S1135:Complete the task associated to this 'TODO' comment", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S1067:Reduce the number of conditional operators", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S3459:Remove unassigned auto-property", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S1144:Remove the unused private set accessor in property", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S4004:property read-only by removing the property setter or making it private", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S1694:Convert this 'abstract' class to a concrete class with a private constructor", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S2292:Make this an auto-implemented property and remove its backing field", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S3925:Update this implementation of 'ISerializable' to conform to the recommended serialization pattern", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S2325:a static method", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S1309:Do not suppress issues", Justification = "Header is defined in stylecop.json")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar.CSharp.DocumentationRules", "S1125:Remove the unnecessary Boolean literal(s)", Justification = "Header is defined in stylecop.json")]
